.TH Turns-n-Layers 1 "July, 2012" Linux "User Manual"
.SH NAME:
Turns-n-Layers \- A coil winding design aid.
.SH SYNOPSIS:
.BI "turns-n-layers" " [\-v \--version]"
.SH DESCRIPTION:
.B turns-n-layers
is a graphical design aid for coil winding for chokes and xfmrs. It calculates
the
.I physical
design, not the electronic. It does help determine if a particular coil will
fit in the available core window.
.P
The project results are displayed in the main window, and may be saved to disk,
or printed.
.P
It should be understood that
.B Turns-n-Layers
calculates the
.I physical
design, not the
.I electronic.
.P See the on-line help for further information.
Turns-n-Layers comes with detailed help documentation that is available
from either the toolbar or the main menu.
.SH OPTIONS:
.TP
\-v \--version: Show the version of the app on standard output, then exit.
.SH DIAGNOSTICS:
.B Turns-n-Layers
includes various message boxes and interactive dialogs to alert the
user to correctable, non-fatal errors. Other dialogs query for
confirmation before performimng any action that could lose data. There
are also diagnostics printed to standard output that are viewable when starting
the app from a command line. These are mainly for debugging/developer maintenance.
.SH AUTHOR:
.B Turns-n-Layers
was written by Simo on a Slackware system. Developed with
the
.I FOX Toolkit
(http://www.fox-toolkit.org), and
.I XEMACS
(http://www.xemacs.org)
.SH REPORT BUGS:
Send bug reports to: simo@furrydolphin.net
.SH COPYRIGHT:
.B Turns-n-Layers
is Copyright (C) 2012 by Simo. This program is free software.
See "COPYING" for text of the GNU Public License.
